customDatabaseDirectory: databases
customHostDirectory: host
directories:
  assemblies: assemblies
  binning: binning
  read_based_annotations: ReadAnnotations
  statistics: statistics
  temp_directory: tmp
host_dbname: human/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index
input: ../test-data
output: output
sample_description: read based annotation, assembly and binning of metagenomes by
  atavide
sample_id: atavide
sequencing: paired
