customDatabaseDirectory: databases
directories:
  assemblies: assemblies
  binning: binning
  prinseq: QC
  read_based_annotations: ReadAnnotations
  statistics: statistics
  temp_directory: tmp
host_dbname: null
host_dbpath: null
input: test-data
output: atavide.out
sample_description: read based annotation, assembly and binning of metagenomes by
  atavide
sample_id: atavide
