customDatabaseDirectory: databases
directories:
  assemblies: assemblies
  binning: binning
  prinseq: QC
  read_based_annotations: ReadAnnotations
  statistics: statistics
  temp_directory: tmp
customHostDirectory: host
input: ../artery_fastq
output: atavide.out
sample_description: read based annotation, assembly and binning of metagenomes by
  atavide
sample_id: atavide
