customDatabaseDirectory: databases
directories:
  assemblies: assemblies
  binning: binning
  read_based_annotations: ReadAnnotations
  statistics: statistics
  temp_directory: tmp
#customHostDirectory: host
#host_dbname: human/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index
customHostDirectory:
input: ../test-data
output: atavide.out
sample_description: read based annotation, assembly and binning of metagenomes by
  atavide
sample_id: atavide
